spring:
  datasource:
    url: jdbc:h2:file:./data/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console